deployments:
- model:
    format: OpenAI
    name: text-embedding-ada-002
    version: '2'
  name: text-embedding-ada-002
  sku:
    capacity: 100
    name: Standard
- model:
    format: OpenAI
    name: gpt-4o
    version: '2024-05-13'
  name: gpt-4
  sku:
    capacity: 1
    name: GlobalStandard
- model:
    format: OpenAI
    name: gpt-4o-mini
    version: '2024-07-18'
  name: gpt-4-evals
  sku:
    capacity: 1
    name: DataZoneStandard